from . import is_trade_partner
from . import is_trade_product
from . import is_trade_purchase_order
from . import is_trade_sales_order
from . import is_account_move_mixin
from . import is_trade_purchase_order_line
from . import is_trade_sales_order_line
from . import is_trade_uom
from . import is_trade_tags
from . import is_partner_category
from . import is_product_category
from . import is_po_so_line
from . import is_customer_invoiсe
from . import is_instock
from . import is_payment_suplier
from . import is_payment_customer
from . import is_account_move
from . import is_account_move_line
from . import is_account_account
from . import is_account_cor_line
from . import is_ci_line
