# ============================================================
# run.toml — конфигурация для draw_graph.py
# Все комментарии ниже — справочные. Меняй значения под себя.
# ============================================================

# --- Где искать входные TOML с графами ---
input_dirs = [
"D:/Entertaiment/Графы/Пример 1"
  # , "D:/Проекты/Диаграммы"
]# Список папок для сканирования
recursive  = true            # Рекурсивно обходить подпапки
include_extensions = ["toml"]# Какие расширения файлов считать графами
exclude_patterns  = []       # Список glob-шаблонов для исключения путей

# ============================================================
# Размещение / раскладка (layout)
# ============================================================
[persist]
# Общая настройка групп auto_*
# Каждая группа описана отдельным блоком.
#   name    — имя группы ("pos", "size", "shape", "fonts", "style", "text")
#   save    — сохранять ли auto_* обратно в [[blocks]]
#   freeze  — замораживать (true → не перезаписывать; false → обычное поведение)


# ============================================================
# Сохранение авто-параметров и поведение записи
# ============================================================

#[[persist.groups]]
#name   = "pos"
#save   = true
#freeze = false
#
#[[persist.groups]]
#name   = "size"
#save   = true
#freeze = false
#
#[[persist.groups]]
#name   = "shape"
#save   = true
#freeze = false
#
#[[persist.groups]]
#name   = "fonts"
#save   = true
#freeze = false
#
#[[persist.groups]]
#name   = "style"
#save   = true
#freeze = false
#
#[[persist.groups]]
#name   = "text"
#save   = true
#freeze = false


[layout]
# Режим компоновки:
#   "layered" — слои по главной оси (рекомендуется)
#   "off"     — раскладка отключена (используются pos/auto_pos как есть)
mode = "layered"

# Направление слоёв:
#   LR (слева → направо) | RL (справа → налево)
#   TB (сверху → вниз)   | BT (снизу → вверх)
direction = "LR"

# Стараться уменьшать пересечения рёбер (эвристика)
minimize_edge_crossings = true

# Разводить блоки, чтобы не налезали друг на друга (пост-обработка)
avoid_node_overlap = true

# Зазор между блоками в одном слое (нормированная доля от высоты/ширины)
# Диапазон: 0..1 (обычно 0.02..0.08)
node_gap = 0.03

# Зазор между слоями по главной оси (нормированная доля)
# Диапазон: 0..1 (обычно 0.06..0.12)
layer_gap = 0.08

# Уважать ручные pos (если у блока задан pos=[x,y], раскладка его не двигает)
respect_fixed_blocks = true

# Привязка для pos/auto_pos при записи (шаг сетки, нормированный)
# 0 — без привязки. Обычно 0.01 (сетка 1%)
grid_snap = 0.01

# Детерминированность (при равных условиях)
deterministic = true
seed = 42

[output]
# Сохранять SVG?
save_svg = true

# Сохранять PNG (требуется установленный cairosvg)?
save_png = true

# DPI для PNG-экспорта
png_dpi = 200

# Автоматически открыть сгенерированный SVG в браузере:
#   "svg" — открыть
#   "none" — не открывать
open_in_browser = "svg"

# ============================================================
# Значения по умолчанию (defaults) — применяются, если в блоке
# нет ручного значения и если нет auto_* (первый запуск).
# ============================================================
[defaults]
# Размер холста в пикселях (W,H). Можно переопределить в файле графа: meta.canvas_size = [W,H]
canvas_size = [1200, 800]

# --- Блок: базовые нормированные размеры (0..1) ---
# Ширина блока как доля ширины холста
# Обычно 0.16..0.28
block.width = 0.10

# Высота шапки (заголовка) как доля высоты холста
# Обычно 0.10..0.14
block.header_height = 0.10

# Высота ОДНОЙ строки свойства как доля высоты холста
# Обычно 0.05..0.08
block.prop_height = 0.06

# --- Форма и стиль блока ---
# Форма: "rect" | "rounded" | "pill" | "ellipse"
block.shape = "rounded"

# Радиус скругления (px) — для rounded/pill
block.corner_radius = 10.0

# Толщина рамки (px)
block.stroke_width = 2.0

# Заливка блока:
#   "none" | "#RRGGBB" | "#RGB" | "rgba(r,g,b,a)" | любые валидные SVG-цвета
block.fill_color = "none"

# Цвет рамки
block.stroke_color = "#000000"

# --- Шрифты ---
# Семейство шрифтов (SVG): "Arial", "Inter", "Roboto", ...
font.family = "Arial"

# Размер шрифта заголовка (px)
font.size_title = 14

# Размер шрифта свойств (px)
font.size_prop  = 12

# Заголовок — жирный?
font.bold_title = true

# Подписи стрелок — курсив?
font.italic_arrow = true

# --- Текст внутри блоков — выравнивание и отступы ---
# Горизонтальное выравнивание заголовка/свойств:
#   "left" → text-anchor="start"
#   "center" → text-anchor="middle"
#   "right" → text-anchor="end"
block.text_align_title = "center"
block.text_align_props = "center"

# Вертикальная привязка текста:
#   "baseline" (обычно лучше для многострочного)
#   "middle"   (геометрическая середина строки; удобно, если центрируешь строку)
block.text_valign_title = "middle"
block.text_valign_props = "middle"

# Внутренние отступы текста (px)
block.text_padding_title_x = 6
block.text_padding_title_y = 6
block.text_padding_prop_x  = 6
block.text_padding_prop_y  = 6

# --- Тема (общие цвета) ---
# Цвет фона холста
theme.background = "#FFFFFF"

# Цвет основного текста в блоках
theme.text_color = "#000000"

# Цвет стрелок
theme.arrow_color = "#222222"

# --- Стрелки (дефолтные стили; могут быть переопределены в [[blocks.outs]]) ---
# Тип линии: "auto" | "straight" | "orthogonal"
style.curve = "auto"

# Позиция подписи на ребре: 0..1 (0 — у начала, 0.5 — по центру, 1 — у конца)
style.label_offset = 0.5

# С какой стороны подключаться к блоку: "auto" | "left" | "right" | "top" | "bottom"
style.connector_from = "auto"
style.connector_to   = "auto"

# Размер наконечника стрелки (множитель; 1.0 — базовый)
style.arrow_size = 1.0

# Толщина линии стрелки (px)
style.arrow_thickness = 2.0
