[INPUT]
# Несколько исходных папок; каждая сканируется рекурсивно.
input_dirs = [
  "D:/Entertaiment/Английский/data/Урок 4"
]
# Какие расширения обрабатывать:
extensions = [".txt"]
# Рекурсивный обход (true/false)
recursive = true

[OUTPUT]
# Корневая папка для результатов.
# ЕСЛИ пусто или параметр отсутствует — писать рядом с исходным файлом.
# output_root = "D://Entertaimant//Английский//! свои рассказы//Урок 4//OUTPUT"

[NAMING]
# Паддинги для главы/подраздела
pad_chapter_to_3 = true
pad_section_to_2 = true
# Разделитель между номером и названием (в имени файла)
title_separator = " "
# Расширение создаваемых файлов
extension = ".txt"
# Для НЕНумерованных заголовков: номер главы по умолчанию (например, 3 → 003_01 ...)
base_chapter = 3

[ADVANCED]
# Игнорировать скрытые элементы (имя начинается с ".")
ignore_hidden = true
# Пропускать файлы, где не найдено ни одной секции
skip_files_without_sections = true
# Кодировки
source_encoding = "utf-8"
output_encoding = "utf-8"
delete_source_after = true

# ---------- БЛОКИ (можно добавлять/удалять/править как угодно) ----------
# Каждый блок: маркеры начала, суффикс для выходного файла, пост-обработка текста.

[[BLOCKS.rules]]
name = "EN"
markers = ["EN:", "English:"]
suffix = "_en"
sentence_per_line = true
remove_empty_lines = false

[[BLOCKS.rules]]
name = "RU"
markers = ["RU:", "Русский:"]
suffix = "_ru"
sentence_per_line = true
remove_empty_lines = false

[[BLOCKS.rules]]
name = "DICT"
markers = ["Новые слова:", ]
suffix = "_di"
sentence_per_line = true
remove_empty_lines = true
