# master_config.toml — новый формат с skip / halt_after и [[steps.params]]
[globals]
input_dirs = ["D:/Entertaiment/Английский/data/Урок 4"]
include_suffixes = ["_en", "_di"]
exclude_suffixes = ["_ru", "_draft"]
output_suffix   = "_bg"
delete_images_after = true

[options]
dry_run = false
continue_on_error = false
backup_configs = false
python_executable = ""

[[steps]]
type = "set_params"
targets = [
  "0_split_lesson_file/config.toml",
  "1_make_audio_tts_from_text/tts_config.toml",
  "2_make_image_to_audio/config.toml",
  "3_make_image_text_overlay/config.toml",
  "4_make_video_from_audio_and_image/config.toml"
]
skip = false
halt_after = false
  [[steps.params]]
  key = "input_dirs"
  use = "global"

[[steps]]
type = "run_script"
script = "0_split_lesson_file/split_lesson_file.py"
args = []
skip = false
halt_after = false

[[steps]]
type = "set_params_and_run"
targets = ["1_make_audio_tts_from_text/tts_config.toml"]
skip = false
halt_after = false
  [[steps.params]]
  key = "input_dirs"
  use = "global"
  [steps.run]
  script = "1_make_audio_tts_from_text/tts_batch_reader.py"
  args = []

[[steps]]
type = "set_params_and_run"
targets = ["2_make_image_to_audio/config.toml"]
skip = false
halt_after = false
  [[steps.params]]
  key = "include_suffixes"
  use = "global"
  [[steps.params]]
  key = "exclude_suffixes"
  use = "global"
  [[steps.params]]
  key = "output_suffix"
  use = "value"
  value = "_bg"
  [steps.run]
  script = "2_make_image_to_audio/make_image_to_audio.py"
  args = []

[[steps]]
type = "run_script"
script = "3_make_image_text_overlay/image_text_overlay.py"
skip = false
halt_after = false

[[steps]]
type = "set_params_and_run"
targets = ["4_make_video_from_audio_and_image/config.toml"]
skip = false
halt_after = false
  [[steps.params]]
  key = "delete_images_after"
  use = "global"
  [steps.run]
  script = "4_make_video_from_audio_and_image/make_video_from_audio_and_image.py"
  args = []
