[io]
input_dirs = ["D:/Entertaiment/Графы/Пример 1"]
recursive = true
input_suffix = ".toml"
include_extensions = ["toml"]
exclude_patterns = []
output_suffix = "_01"

[migration]
wipe_auto_fields = true
dedupe_outs = true
