# config_prepare.toml — Этап 01: подготовка / нормализация
# ВАЖНО: Комментарии исходника не сохраняются (канонизация).

[io]
# Где искать входные TOML
input_dirs = ["D:/Entertaiment/Графы/Пример 1"]
recursive = true
# Исключить уже подготовленные файлы (чтобы не делать *_01_01.toml)
exclude_patterns = ["*_01.toml", "*_02.toml", "*_03.toml"]
# Что считаем «сырым» (матч по окончанию имени файла, регистронезависимо)
input_suffix = ".toml"
# Суффикс для нового файла перед .toml
output_suffix = "_01"

[behavior]
# Сохранение оригинальных фрагментов:
# false | "inline" | "appendix"
keep_original = false

[aliases]
# Синонимы для блоков — и заголовков, и шортката "block = ..."
blocks = ["blocks","блоки","block","блок","node","узел"]

[aliases.fields]
outs       = ["outs","выходы","стрелки","edges"]
properties = ["properties","параметры","свойства","props"]
title      = ["title","заголовок","название"]
id         = ["id","ид","идентификатор","ключ"]
