# ===============================
# 01_prepare — конфигурация этапа нормализации и миграции графов
# ===============================
# Назначение: привести входные TOML к единому формату (миграция стрелок, очистка auto_*, дедупликация и т.п.)
# Все промежуточные файлы пишутся В ТУ ЖЕ ПАПКУ, что и исходный .toml, с суффиксом: .s01.prepared.toml
#
# Советы:
# - Сначала запустите с `dry_run = true`, чтобы увидеть отчёт без изменений файлов.
# - Если хотите обрабатывать только специальные файлы (например, *.graph.toml), поменяйте input_suffix.
# - Путь разделяйте символом '/', чтобы конфиги были кроссплатформенными.

[io]
# --- Где искать входные TOML с графами ---
input_dirs = [
    "D:/Entertaiment/Графы/Пример 1"
    # , "D:/Проекты/Диаграммы"
] # Список папок для сканирования

# Обход подпапок: true — рекурсивно; false — только указанные папки
recursive = true

# Какой СУФФИКС искать у входных файлов для этого этапа.
# Примеры:
#   ".toml"             — все TOML
#   ".graph.toml"       — только «сырые» файлы графов (если вы так их называете)
#   ".flow.toml"        — любой ваш собственный суффикс
input_suffix = ".toml"

# Дополнительная грубая фильтрация по расширению (обычно оставьте как есть)
include_extensions = ["toml"]

# Исключения (glob-шаблоны). Примеры:
#   "**/_archive/**", "**/tmp/**", "**/*.bak.toml"
exclude_patterns = []

# Режим записи вывода:
#   "new"     — писать новый файл рядом с исходником (рекомендуется)
#   "inplace" — перезаписывать исходный файл (используйте backup_original=true)
write_mode = "new"

# Делать ли бэкап исходника при inplace-записи (создаст *.bak)
backup_original = false

# Пробный запуск без записи файлов
dry_run = false

# Остановить этап при первой критичной ошибке (true) или продолжать (false)
stop_on_error = true

[migration]
# Конвертация устаревших конструкций в [[blocks.outs]]
convert_arrows = true            # [[arrows]] -> [[blocks.outs]] / outs=[...] -> [[blocks.outs]]
remove_global_arrows = true      # Удалить глобальные [[arrows]] разделы
wipe_auto_fields = true          # Удалить все auto_* поля (позиции/размеры/шрифты и т.д.)
dedupe_outs = true               # Убрать дубликаты исходящих связей у блока

[normalize]
# Нормализация структуры и форматирования
sort_keys = true                 # Единый порядок ключей в блоках
newline = "LF"                   # "LF" (Unix) | "CRLF" (Windows)
encoding = "utf-8"               # Кодировка файла вывода (фиксировано UTF-8)
