# === Общие параметры входа/выхода ===
# Список папок для обхода (рекурсивно, если recursive=true)
input_dirs = ["D://Entertaimant//Английский//! свои рассказы//Урок 2",
"D://Entertaimant//Английский//! свои рассказы//Урок 3"]
#input_dirs = ["D://Entertaimant//Английский//! свои рассказы//Видео2"]
#input_dirs = ["./input"]
# Явный список файлов изображений (если нужно точечно)
input_files = []

# Рекурсивный обход папок
recursive = true

# Расширения изображений
image_extensions = [".jpg", ".jpeg", ".png", ".webp"]

# Имя/расширение текстового файла-пары (строго .txt)
text_extension = ".txt"

# Кодировка текстовых файлов
text_encoding = "utf-8"

# === Поиск картинок для текста ===
# image_match_mode определяет, какие картинки считаются "парами" к тексту:
#
#   "exact"  — искать только картинку с точно таким же именем, как у текста
#              (пример: promo.txt → promo.jpg / promo.png / promo.webp).
#
#   "prefix" — искать все картинки, имя которых начинается с имени текстового файла,
#              включая варианты с суффиксами.
#              (пример: promo.txt → promo.jpg, promo_1.png, promo-final.png,
#                        promo v3.png, promo@2x.webp, promo (copy).jpeg).
#
# То есть:
# - exact  = один текст → одна картинка (строгое совпадение).
# - prefix = один текст → несколько картинок (все, начинающиеся с этого имени).
#
# Рекомендуется "prefix", если к одному тексту может быть несколько версий картинки
# (разные размеры, версии, варианты).
# Если всегда "один текст ↔ одна картинка", то можно поставить "exact".
image_match_mode = "prefix"

# Куда сохранять результат ("" = рядом с исходником; иначе — в эту папку, будет создана)
output_dir = ""
#output_dir = "./output"

# Схема имени выходного файла:
# "suffix"         — имя + "_with_text" (без перезаписи исходников)
# "overwrite"      — перезаписывать исходник
# "skip_if_exists" — пропускать, если выходной уже существует
output_naming = "overwrite"

# Суффикс для режима "suffix"
output_suffix = "_tx"



# === Наложение текста ===
# Путь к TTF/OTF-шрифту (обязателен!)
font_path = "C:/Windows/Fonts/arial.ttf"

# Размер шрифта: число или "auto"
font_size = "auto"

# Минимальный размер шрифта при автоподборе (см)
min_font_size = 14

# Цвет текста (белый)
color = "#FFFFFF"

# Стиль читабельности (фон/контур):
# Варианты:
#  - "none"  — без улучшений
#  - "stroke" — только контур
#  - "box"   — полупрозрачная подложка под текст
#  - "both"  — и подложка, и контур
readability_style = "none"

# Контур текста (для "stroke" и "both")
stroke_width = 2
stroke_fill = "#000000"

# Подложка под текст (для "box" и "both"), RGBA в формате #RRGGBBAA
#background_box_fill = "#00000080"  # чёрный, 50% непрозрачность
background_box_fill = "#00000040"  # чёрный, 25 непрозрачность

# Выравнивание строк: "left" | "center" | "right"
align = "center"

# Позиция текста (якорь):
# "top_left","top_center","top_right",
# "center_left","center","center_right",
# "bottom_left","bottom_center","bottom_right"
anchor = "center"

# Отступы от краёв (пиксели)
margin_x = 32
margin_y = 32

# Максимальная ширина/высота области под текст (в долях от размеров изображения)
max_width_pct = 0.90
max_height_pct = 0.90

# Межстрочный интервал (множитель к высоте строки)
line_spacing = 1.20


# === Прочее ===
# Учитывать EXIF-ориентацию (чтобы текст был поверх правильной ориентации)
respect_exif_orientation = true

# Принудительный формат сохранения: "" = как у исходника; или "JPEG"/"PNG"/"WEBP"
save_format = ""

# Качество (где применимо)
jpeg_quality = 90
webp_quality = 90

# Логи
logging_level = "INFO"
log_to_file = false
log_file = "overlay.log"

# Сухой запуск: true = только отчёт, файлы не пишутся
dry_run = false


#Чёрный фон (разная прозрачность)
#000000FF → чёрный полностью непрозрачный
#000000CC → чёрный ~80% непрозрачности
#00000080 → чёрный ~50% (как в примере)
#00000040 → чёрный ~25%
#00000020 → чёрный ~12%

#Белый фон
#FFFFFFFF → белый полностью непрозрачный
#FFFFFFCC → белый 80%
#FFFFFF80 → белый 50%
#FFFFFF40 → белый 25%

#Серый фон
#808080FF → серый полностью непрозрачный
#80808080 → серый 50%
#80808040 → серый 25%

#Цветные примеры
#FF000080 → красный 50%
#00FF0080 → зелёный 50%
#0000FF80 → синий 50%
#FFFF0080 → жёлтый 50%
#00FFFF80 → бирюзовый 50%
#FF00FF80 → пурпурный 50%