# config_render.toml — Этап 03: строгий рендер
# Ничего не вычисляем; читаем (РУЧНЫЕ > AUTO_* > DEFAULTS).
# Параметр open_after_render — открыть SVG в браузере после генерации.

[io]
input_dirs = [
  "D:/Entertaiment/Графы/Пример 1"
]
recursive = true
include_extensions = ["toml"]
exclude_patterns = []
input_suffix = "_02.toml"
output_suffix = "_03"
dry_run = false

[output]
save_png = false
png_dpi = 200
open_after_render = true      # ОТКРЫТЬ результат в браузере: true|false (Windows/macOS/Linux)

[strict]
missing_pos = "error"         # "error" | "grid"

[defaults]
canvas_size = [1200, 800]
block.width = 0.10
block.header_height = 0.10
block.prop_height   = 0.06
block.shape = "rounded"
block.corner_radius = 10.0
block.stroke_width  = 2.0
block.fill_color    = "none"
block.stroke_color  = "#000000"
font.family = "Arial"
font.size_title = 14
font.size_prop  = 12
font.bold_title = true
font.italic_arrow = true
block.text_align_title = "center"
block.text_align_props = "center"
block.text_valign_title = "middle"
block.text_valign_props = "middle"
block.text_padding_title_x = 6
block.text_padding_title_y = 6
block.text_padding_prop_x  = 6
block.text_padding_prop_y  = 6
theme.background = "#FFFFFF"
theme.text_color = "#000000"
theme.arrow_color = "#222222"
style.curve = "orthogonal"    # auto|straight|orthogonal
style.label_offset = 0.5
style.connector_from = "right"
style.connector_to   = "left"
style.arrow_size = 1.0
style.arrow_thickness = 2.0


# --- Разделители между строками свойств ---
block.props_dividers = true           # Включить горизонтальные линии между строками свойств: true|false
block.props_divider_thickness = 1.0   # Толщина линий (px); если 0 — берем половину толщины рамки
