{
    'name': 'BT Trade',
    'summary': 'Buy and Sell',
    'category': '',
    'version': '0.0.0.1',
    'author': 'Bohdan',
    'support': '',
    'website': '',
    'license': 'OPL-1',
    'depends': [
        'base',
        'web'
    ],

    'data': [
        'security/ir.model.access.csv',
        'data/bt_sequence.xml',
        'data/bt_account_account_data.xml',
        'reports/bt_purchase_order_report_template.xml',
        'reports/bt_purchase_order_report.xml',
        'reports/bt_customer_invoice_report_template.xml',
        'reports/bt_customer_invoice_report.xml',
        'views/bt_root_menu.xml',
        'views/bt_uom_views.xml',
        'views/bt_partner_views.xml',
        'views/bt_partner_group_views.xml',
        "views/bt_product_views.xml",
        'views/bt_product_category_views.xml',
        'views/bt_purchase_order_views.xml',
        'views/bt_sale_order_views.xml',
        'views/bt_purchase_order_line_views.xml',
        'views/bt_sale_order_line_views.xml',
        'views/bt_po_line_so_line_views.xml',
        'views/bt_tags_views.xml',
        'wizard/bt_po_so_ines_wizard_views.xml',
        'views/bt_customer_invoice_views.xml',
        'views/bt_ci_line_views.xml',
        'views/bt_in_stock_views.xml',
        'views/bt_is_line_views.xml',
        'views/bt_payment_customer_views.xml',
        'views/bt_payment_supplier_views.xml',
        'views/bt_account_move_views.xml',
        'views/bt_account_move_line_views.xml',
        'wizard/bt_lost_am_wizard_views.xml',
        'views/bt_account_cor_line_views.xml',
        'views/bt_warehouse_views.xml',
        'views/bt_stock_picking_views.xml',
        'views/bt_stock_picking_line_views.xml',
        'views/bt_stock_move_views.xml',
        'views/bt_stock_move_line_views.xml',
        'views/bt_ci_refund_views.xml',
        'views/bt_is_refund_views.xml',
        'views/bt_inventory_views.xml',
        'views/bt_menus.xml',
    ],

    'images': [
        'static/img/icons/bt_icon.png'
    ],

    'application': True,
}