{
    'name': 'IS trade',
    'summary': 'Buy-Sell module',
    'category': '',
    'version': '0.0.0.1',
    'author': 'Turbo UA',
    'support': ' ',
    'website': ' ',
    'license': 'OPL-1',
    'depends': [
        'base',
    ],

    'data': [
        'security/ir.model.access.csv',
        'wizard/is_lost_am_wizard_views.xml',
        'views/main_menu.xml',
        'views/is_trade_partner_view.xml',
        'views/is_trade_product_view.xml',
        'views/is_trade_purchase_order.xml',
        'views/is_trade_sales_order.xml',
        'views/is_trade_sales_order_line.xml',
        'views/is_trade_purchase_order_line.xml',
        'views/is_trade_uom_view.xml',
        'views/is_trade_tags_view.xml',
        'views/is_partner_category_view.xml',
        'views/is_product_category_view.xml',
        'views/is_po_so_line_views.xml',
        'views/is_instock_view.xml',
        'views/is_customer_invoice_view.xml',
        'views/is_payment_supplier_view.xml',
        'views/is_account_move_line.xml',
        'views/is_account_move.xml',
        'views/is_account_account.xml',
        'views/is_ci_line_views.xml',
        'views/is_account_cor_line_views.xml',
        'wizard/is_wizard_view.xml',
        'reports/is_trade_purchase_order_report.xml',
        'reports/is_trade_purchase_order_template.xml',
        'reports/is_customer_ invoice_template.xml',
        'reports/is_customer_invoice_report.xml',
        'data/so_sequence.xml',
        'data/po_sequence.xml',
        'data/is_sequence.xml',
        'data/ci_sequence.xml',
        'data/ps_sequence.xml',
        'data/pc_sequence.xml',
        'data/am_sequence.xml',
        'data/am_line_sequence.xml',
        'data/is_account_account_data.xml',
    ],

    'images': [
        'static/description/icon.png'
    ],

    'application': True,
    'installable': True,
    'auto_install': False,
}
