# =========================
# Конфигурация TTS Batch Reader (TOML)
# =========================
# Комментарии начинаются с "#".
# Рядом со скриптом tts_batch_reader.py должен лежать этот файл tts_config.toml.

# ---------------- ВХОД ----------------

# Если true — создаём отдельные MP3 для каждого EN-голоса из alt_voices.
multi_en_outputs = false
# Голосовые маркеры: (v:алиас) или (voice:алиас).
voice_marker_prefixes = ["v:", "voice:"]
# Если алиас не найден в voice_aliases — искать по подстроке среди [voice] + alt_voices.
allow_partial_voice_match = true

# Можно указывать папки и/или маски (относительные и абсолютные пути).
input_dirs = ['D:/Entertaiment/Английский/data/Урок 4']


# Было: "recursive_inputs". Теперь: "recurse".
# Если true — маски без ** дополнительно расширяются до рекурсивных; папки обходятся рекурсивно.
recurse = true

# Какие расширения брать (с точкой).
extensions = [".txt"]

# --- Фильтрация по суффиксам (только эти два параметра) ---
# Если список НЕ ПУСТОЙ — берём ТОЛЬКО файлы с этими суффиксами в конце имени (без расширения).
# Если список ПУСТОЙ — ограничение не применяется.
include_suffixes = ['_en', '_di']

# Файлы, чьё имя (без расширения) заканчивается на любой из этих суффиксов — исключаются
exclude_suffixes = ['_ru','_draft', '_ua']



# Какие языки озвучивать по умолчанию, если не сработал жёсткий суффикс.
enable_languages = ["en", "ua"]

# ---------------- (справка) Примеры входов ----------------
[reference]
example_inputs = [
  "D:\\\\Work_Odoo\\\\OdooDev\\\\_tu_helper\\\\_Py_script\\\\tts\\\\data\\\\Стих",
  "D:\\\\Work_Odoo\\\\OdooDev\\\\_tu_helper\\\\_Py_script\\\\tts\\\\data\\\\Урок 4\\\\*.txt",
  "data/*.txt",
  "notes",
  "data"
]
# Полный набор языков, который ты иногда включал
enable_languages_all = ["en", "ru", "uk"]

# ---------------- ЯЗЫКИ ----------------
# Описание каждого языка: voice, alt_voices, strict_no_fallback, markers,
# detect_prefixes, а также вложенные таблицы suffix_filter и voice_aliases.

# === Английский (EN) ===
[languages.en]
voice              = "en-GB-SoniaNeural"
alt_voices         = [
  "en-GB-RyanNeural",
  "en-GB-SoniaNeural",
  "en-US-GuyNeural",
  "en-US-RogerNeural",
  "en-US-SteffanNeural",
  "en-US-JennyNeural",
  "en-US-AriaNeural",
  "en-US-MichelleNeural",
  "en-AU-WilliamNeural",
  "en-AU-NatashaNeural"
]
# (справка) Полный список EN-голосов — каталог для выбора (скрипт не использует напрямую):
all_voices_en = [
  "en-GB-RyanNeural",
  "en-GB-ThomasNeural",
  "en-GB-LibbyNeural",
  "en-GB-MaisieNeural",
  "en-GB-SoniaNeural",
  "en-US-GuyNeural",
  "en-US-RogerNeural",
  "en-US-SteffanNeural",
  "en-US-JennyNeural",
  "en-US-AriaNeural",
  "en-US-MichelleNeural",
  "en-US-AnaNeural",
  "en-US-KidNeural",
  "en-AU-WilliamNeural",
  "en-AU-NatashaNeural"
]
strict_no_fallback = true
markers            = ["[EN]", "_en_", "(en)", "en:", "english:"]
detect_prefixes    = ["en"]

[languages.en.suffix_filter]
enabled = true
suffix  = "_en"

[languages.en.voice_aliases]
ryan    = "en-GB-RyanNeural"
thomas  = "en-GB-ThomasNeural"
guy     = "en-US-GuyNeural"
steffan = "en-US-SteffanNeural"

# === Русский (RU) ===
[languages.ru]
voice              = "ru-RU-DmitryNeural"
# (справка из JSON): alt_voices_ru — оставлено как памятка
alt_voices_ru      = ["ru-RU-SergeyNeural", "ru-RU-AndreiNeural", "ru-RU-DmitryNeural", "ru-RU-SvetlanaNeural"]
# Рабочее поле:
alt_voices         = ["ru-RU-SergeyNeural", "ru-RU-AndreiNeural", "ru-RU-DmitryNeural", "ru-RU-SvetlanaNeural"]
strict_no_fallback = true
markers            = ["[RU]", "[RUS]", "_ru_", "_рус_", "(ru)", "(рус)", "ru:", "рус:", "russian:"]
detect_prefixes    = ["ru"]

[languages.ru.suffix_filter]
enabled = true
suffix  = "_ru"

[languages.ru.voice_aliases]
dmitry   = "ru-RU-DmitryNeural"
sergey   = "ru-RU-SergeyNeural"
andrei   = "ru-RU-AndreiNeural"
svetlana = "ru-RU-SvetlanaNeural"

# === Украинский (UA) ===
[languages.ua]
voice              = "uk-UA-OstapNeural"
alt_voices         = ["uk-UA-PolinaNeural","uk-UA-OstapNeural"]
strict_no_fallback = true
markers            = ["[UK]", "[UA]", "_uk_", "_ua_", "(uk)", "(ua)", "uk:", "ua:", "ukrainian:"]
detect_prefixes    = ["uk"]

[languages.ua.suffix_filter]
enabled = true
suffix  = "_ua"

[languages.ua.voice_aliases]
ostap  = "uk-UA-OstapNeural"
polina = "uk-UA-PolinaNeural"

# ---------------- ОЧИСТКА / ПАУЗЫ ----------------

# Символы, которые нужно полностью убрать из озвучки.
strip_symbols = ["(", ")", "[", "]", "{", "}", "_", "<", ">", "—"]

# Удалять эмодзи/«экзотику».
strip_emojis = true

# Скорость речи (%). Отрицательное — медленнее.
rate = -15

# Паузы. (Пауза имитируется добавлением запятых ≈ 300 мс / запятая)
[pauses]
between_phrases_ms           = 600
start_of_line_extra_pause_ms = 600
sentence_delimiters          = [".", ";", "!", "?", "\n"]  # маркер языка действует до ближайшего разделителя

[pauses.space_pause]
enabled      = false
ms_per_space = 1   # пауза за КАЖДЫЙ пробел подряд (мс/пробел). 0 — отключено.

[pauses.newline_pause]
enabled        = true
ms_per_newline = 600  # пауза за КАЖДЫЙ перенос строки (учитываются и пустые строки), мс.

# ---------------- Фильтрация/пропуск текста перед озвучкой ----------------
# Глобальные правила (не привязаны к языку).
[filters]
debug_dump = true
bracket_pairs = [
  ["[[", "]]"],
  ["{{", "}}"],
  ["((", "))"],
  ["//", "//"]
]
