# ==============================
# Конфигурация генерации картинок по аудиофайлам
# ФОРМАТ: TOML. Файл должен лежать в том же каталоге, что и make_image_from_audio.py
# ==============================

# --- Вход ---
# Папка, где искать аудиофайлы. Можно оставить пустым, если используете input_files.
#input_dir = "D:/Media/Audio"     # пример; "" — не использовать папку
#input_dir = "D://Entertaimant//Английский//! свои рассказы//Видео2"     # пример; "" — не использовать папку
#input_dir = "D://Entertaimant//Английский//! свои рассказы//Урок 3"     # пример; "" — не использовать папку

input_dirs = ['D:/Entertaiment/Английский/data/Урок 4']

#  "D://Entertaimant//Английский//! свои рассказы//Урок 2",
#  "D://Entertaimant//Английский//! свои рассказы//Урок 3"

recursive = true                 # рекурсивный обход подпапок

# Явный список аудиофайлов (опционально). Пути абсолютные или относительные.
# Если задан и input_dir, результаты объединяются, дубликаты удаляются.
input_files = [
    # "D:/Media/one.wav",
    # "D:/Media/two.mp3",
]

# Расширения аудио (без учёта регистра)
audio_exts = [".mp3", ".wav", ".m4a", ".flac", ".aac", ".ogg"]

# --- Фильтрация по суффиксам (только эти два параметра) ---
# Файлы, чьё имя (без расширения) заканчивается на любой из этих суффиксов — исключаются
exclude_suffixes = ['_ru', '_draft']

# Если список НЕ ПУСТОЙ — берём ТОЛЬКО файлы с этими суффиксами в конце имени (без расширения).
# Если список ПУСТОЙ — ограничение не применяется.
include_suffixes = ['_en', '_di']

# --- Выход ---
# Куда сохранять картинки. "" или отсутствие параметра — рядом с исходным аудио.
output_dir = ""                  # "" => рядом с аудио
mirror_subdirs = true            # Если output_dir задан, повторять структуру подпапок входа
output_suffix = '_bg'            # Суффикс к имени картинки. "" = без суффикса (например: song_bg.png)

# Политика при конфликте имён:
#  - "skip"      — пропустить, если файл уже существует
#  - "overwrite" — перезаписать
#  - "rename"    — добавлять суффикс _1, _2, ...
conflicts = "overwrite"

# Сухой прогон: ничего не создаём, только показываем, что бы сделали.
dry_run = false

# Количество рабочих потоков (0 или 1 — однопоточно)
workers = 0

# Файл лога. "" — только консоль.
log_file = ""


# --- Параметры изображения ---
[image]
width = 1920
height = 1080
format = "png"                   # "png" | "jpg" | "webp"
jpeg_quality = 90                # 1..95, влияет на jpg/webp

# Варианты фона (выберите один и закомментируйте остальные)

# 1) Однотонный цвет:
[image.background]
type = "color"
# --- Основные цвета ---
#value = "#000000"   # Чёрный
#value = "#FFFFFF"   # Белый
#value = "#808080"   # Серый
#value = "#C0C0C0"   # Светло-серый
#value = "#404040"   # Тёмно-серый

# --- Красные/оранжевые ---
#value = "#FF0000"   # Красный
#value = "#800000"   # Тёмно-красный (бордовый)
#value = "#FFA500"   # Оранжевый
#value = "#FFFF00"   # Жёлтый

# --- Зелёные ---
#value = "#008000"   # Зелёный
#value = "#00FF00"   # Лайм (ярко-зелёный)

# --- Синие ---
#value = "#0000FF"   # Синий
#value = "#000080"   # Тёмно-синий
#value = "#00BFFF"   # Голубой (DeepSkyBlue)

# --- Голубые/бирюзовые ---
#value = "#40E0D0"   # Бирюзовый (Turquoise)
#value = "#00CED1"   # Тёмный бирюзовый (DarkTurquoise)

# --- Фиолетовые/розовые ---
#value = "#800080"   # Фиолетовый (Purple)
#value = "#8A2BE2"   # Сине-фиолетовый (BlueViolet)
#value = "#FFC0CB"   # Розовый (Pink)
#value = "#FF69B4"   # Ярко-розовый (HotPink)

# --- Коричневые/бежевые ---
#value = "#8B4513"   # Коричневый (SaddleBrown)
#value = "#D2B48C"   # Бежевый (Tan)
#value = "#F5F5DC"   # Светло-бежевый (Beige)

# --- С прозрачностью ---
#value = "#00000080" # Чёрный 50% прозрачности
#value = "#FF000080" # Красный 50% прозрачности
#value = "#FFFFFF80" # Белый 50% прозрачности

# --- Выбранный цвет (по умолчанию) ---
value = "#1E1E1E"    # Тёмно-серый (как фон VS Code)

# 2) Градиент:
# [image.background]
# type = "gradient"
# from = "#0F2027"
# to = "#2C5364"
# direction = "vertical"         # "vertical" | "horizontal"

# 3) Фоновая картинка:
# [image.background]
# type = "image"
# path = "D:/Media/backgrounds/bg.jpg"
# fit = "cover"                  # "contain" | "cover" | "stretch"
